apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webserver-deployment.yaml
  - webserver-service.yaml
images:
  - name: nginx
    newName: 765075434223.dkr.ecr.us-east-2.amazonaws.com/webserver # {"$imagepolicy": "flux-system:gitops-demo:name"}
    newTag: main-719b816-1625066799 # {"$imagepolicy": "flux-system:gitops-demo:tag"}
